### ISSUE TITLE
feat: set SENTRY_RELEASE env

### ISSUE THREAD

**Issue by spondbob** [getsentry/sentry-netlify-build-plugin#11]
I'm not sure if this is just my setup, but I found that new issues didn't get linked to any release created - it said Release: n/a in the sidebar.

Checking out the doc at [Sentry.init({ release })](https://docs.sentry.io/error-reporting/configuration/?platform=node#release) option I was wondering if this could be the reason - Sentry client didn't know where to link the issue. I scanned through the index.js file and didn't see anything is set for `SENTRY_RELEASE`.

I'm not aware if you can set env variable in Netlify through some API call, only thing I found is to set it through [netlify.toml](https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file) which means we need to update this file early before the build starts to insert some thing like `SENTRY_RELEASE=process.env.COMMIT_REF` CMIIW.

**Comment by jonesphillip** [comment]
@spondbob you are correct, in addition to using this build plugin you must also set the release in your SDK init. I've updated the readme to reflect this. There are a number of ways to access access the release in your SDK init. This is a good source of inspiration if you're still looking to do this (specifically the part with the setWebpackConfig):
https://cra.mr/instrumenting-gatsbyjs-with-sentry/
