### ISSUE TITLE
If I am using the gatsby sdk/plugin, do I still use the netlify-build-plugin

### ISSUE THREAD

**Issue by camsloanftc** [getsentry/sentry-netlify-build-plugin#15]
I am configuring the [official gatsby sdk](https://www.gatsbyjs.org/packages/@sentry/gatsby/), and also looking at using this plugin (for my Netlify functions error handling). Could you specify where the line of separation is between them? Should I be using both, or only one?

Thanks!

**Comment by jonesphillip** [comment]
@camsloanftc good question. You should use both. The Sentry SDK for Gatsby handles the instrumenting of your code with Sentry. The Netlify Build Plugin handles letting Sentry know about your source maps and deploys.

Closing this out, but let me know if you have any further questions.

**Comment by camsloanftc** [comment]
Thanks @jonesphillip! Very much appreciated. That does solve the problem.

It could be a nice addition to clarify a bit further (on the readme I suppose). I ended up using both, and additionally added the SDK to my Netlify function lambdas as well.

Reading over the readme again after your comment, it makes sense. I can see that the readme says what the plugin does, but I think it was still confusing (to me anyways as an outsider looking in) about what it does not do. 

Maybe a line like:

```markdown
This plugin does not:
- handle error reporting etc for your applications. You should still use the appropriate SDK for your applications.
```

or 

```
This plugin is intended to be used alongside, not replace, our additional SDKs for your application (such as @sentry/browser or @sentry/node).
```

I might be in the minority here, so definitely not necessary to add. It looks like I am the first person to have the issue so maybe just see if it comes up again.

Thanks for your help!

**Comment by calebfaruki** [comment]
This deserves a lot more clarification and should be re-opened.

> @camsloanftc good question. You should use both. The Sentry SDK for Gatsby handles the instrumenting of your code with Sentry. The Netlify Build Plugin handles letting Sentry know about your source maps and deploys.
> 
> Closing this out, but let me know if you have any further questions.

Sentry SDK for Gatsby does more than just instrumentation. It's a wrapper for the CLI, which also notifies Sentry of releases.

If this plugin is meant to interact with your configurations, it should be clearly documented and have a debug mode. If not, this plugin just adds noise. I've spent days fussing with the source map configuration and I have little idea of whether its the Netlify plugin that is to blame or my own custom configuration.

In either case, I would rather use my own custom configuration if it's that brittle.
