### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by AsimNet** [getsentry/sentry-netlify-build-plugin#23]
hello,
when I added the plugin to my Netlify site, I encounter this issue:

![image](https://user-images.githubusercontent.com/3624441/91173252-2ec8ce80-e6e6-11ea-888e-a2a219521027.png)

**Comment by jonesphillip** [comment]
@AsimNet does this still happen? From your output I can't see anything related to this build plugin. Can you provide more information here?

**Comment by AsimNet** [comment]
you are right, it was related to Netlify memory allocation size limit
@jonesphillip
