### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by ehmicky** [getsentry/sentry-netlify-build-plugin#3]
Uncaught exceptions are reported to users as plugin bugs.

We've got some utilities [documented here](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#error-reporting) like `utils.build.failBuild()` which help fine tune error reporting. Ideally, every user error (as opposed to plugin errors) should be caught in a `try`/`catch` and reported with a method like `utils.build.failBuild()`.

This includes for example when there is [no authorization token](https://github.com/getsentry/sentry-netlify-build-plugin/blob/98a1d3bc6fd1f730c9b02d019c826da4416e83d9/index.js#L62). 
What do you think?

**Comment by jonesphillip** [comment]
@ehmicky closed out the no repositories configured issue. Will try to address this when I have the chance

**Comment by ehmicky** [comment]
Thanks! 
Yes, the `No repositories are configured in Sentry for your organization.` should probably also be reported as a user error.

**Comment by jonesphillip** [comment]
@ehmicky believe https://github.com/getsentry/sentry-netlify-build-plugin/pull/8 should resolve this. Let me know if you see anything else.

**Comment by ehmicky** [comment]
Sweet!
When you find any time for it, feel free to update the version by sending a PR to https://github.com/netlify/plugins. Thanks!

**Comment by jonesphillip** [comment]
@ehmicky done!
