### ISSUE TITLE
Prevents Deploy if Sentry Down

### ISSUE THREAD

**Issue by cancan101** [getsentry/sentry-netlify-build-plugin#37]
Right now Sentry is down:
![image](https://user-images.githubusercontent.com/51059/104355613-ecf3c580-54d8-11eb-85b0-5468db1e55f7.png)

and that is preventing being able to deploy on Netlify:

```
1:09:02 PM:   3. onPostBuild command from @sentry/netlify-build-plugin      
1:09:02 PM: ────────────────────────────────────────────────────────────────
1:09:02 PM: ​
1:09:02 PM: Creating new release with version:  5c5370d258279e0cb7ec7de10a651239f5fffb96
1:09:02 PM: ​
1:09:02 PM: ────────────────────────────────────────────────────────────────
1:09:02 PM:   Plugin "@sentry/netlify-build-plugin" internal error          
1:09:02 PM: ────────────────────────────────────────────────────────────────
1:09:02 PM: ​
1:09:02 PM:   Error message
1:09:02 PM:   Error: Command failed: /opt/build/repo/.netlify/plugins/node_modules/@sentry/cli/sentry-cli releases new 5c5370d258279e0cb7ec7de10a651239f5fffb96
1:09:02 PM:   error: API request failed
1:09:02 PM:     caused by: sentry reported an error: bad gateway (http status: 502)
1:09:02 PM: ​
1:09:02 PM:   Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
1:09:02 PM:   Please attach the full debug log to all bug reports.
1:09:02 PM: ​​
1:09:02 PM:   Plugin details
1:09:02 PM:   Package:        @sentry/netlify-build-plugin
1:09:02 PM:   Version:        1.0.4
1:09:02 PM:   Repository:     git+https://github.com/getsentry/sentry-netlify-build-plugin.git
1:09:02 PM:   npm link:       https://www.npmjs.com/package/@sentry/netlify-build-plugin
1:09:02 PM:   Report issues:  https://github.com/getsentry/sentry-netlify-build-plugin/issues
1:09:02 PM: ​
1:09:02 PM:   Error location
1:09:02 PM:   In "onPostBuild" event in "@sentry/netlify-build-plugin" from netlify.toml
1:09:02 PM:       at ChildProcess.exithandler (child_process.js:303:12)
1:09:02 PM:       at ChildProcess.emit (events.js:310:20)
1:09:02 PM:       at maybeClose (internal/child_process.js:1021:16)
1:09:02 PM:       at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
1:09:02 PM: ​
1:09:02 PM:   Error properties
1:09:02 PM:   {
1:09:02 PM:     killed: false,
1:09:02 PM:     code: 1,
1:09:02 PM:     signal: null,
1:09:02 PM:     cmd: '/opt/build/repo/.netlify/plugins/node_modules/@sentry/cli/sentry-cli releases new 5c5370d258279e0cb7ec7de10a651239f5fffb96'
1:09:02 PM:   }
```

**Comment by sdzharkov** [comment]
Experiencing the same issue currently, it is preventing the builds from running.

**Comment by vishalmarneni** [comment]
Experiencing the same issue 

` ────────────────────────────────────────────────────────────────
10:19:36 AM:   3. @sentry/netlify-build-plugin (onPostBuild event)           
10:19:36 AM: ────────────────────────────────────────────────────────────────
10:19:36 AM: ​
10:19:36 AM: Creating new release with version:  9f77c2af337d282044988d70e0e620e3f5bd7b54
10:19:36 AM: ​
10:19:36 AM: ────────────────────────────────────────────────────────────────
10:19:36 AM:   Plugin "@sentry/netlify-build-plugin" failed                  
10:19:36 AM: ────────────────────────────────────────────────────────────────
10:19:36 AM: ​
10:19:36 AM:   Error message
10:19:36 AM:   Error: SentryCLI failed to create a new release. You do not have permission to perform this action. (http status: 403)
10:19:36 AM: ​
10:19:36 AM:   Plugin details
10:19:36 AM:   Package:        @sentry/netlify-build-plugin
10:19:36 AM:   Version:        1.1.0
10:19:36 AM:   Repository:     git+https://github.com/getsentry/sentry-netlify-build-plugin.git
10:19:36 AM:   npm link:       https://www.npmjs.com/package/@sentry/netlify-build-plugin
10:19:36 AM:   Report issues:  https://github.com/getsentry/sentry-netlify-build-plugin/issues
10:19:36 AM: ​
10:19:36 AM:   Error location
10:19:36 AM:   In "onPostBuild" event in "@sentry/netlify-build-plugin" from netlify.toml
10:19:36 AM:       at createSentryRelease (/.netlify/plugins/node_modules/@sentry/netlify-build-plugin/index.js:91:26)`

**Comment by vishalmarneni** [comment]
> Right now Sentry is down: ![image](https://user-images.githubusercontent.com/51059/104355613-ecf3c580-54d8-11eb-85b0-5468db1e55f7.png)
> 
> and that is preventing being able to deploy on Netlify:
> 
> ```
> 1:09:02 PM:   3. onPostBuild command from @sentry/netlify-build-plugin      
> 1:09:02 PM: ────────────────────────────────────────────────────────────────
> 1:09:02 PM: ​
> 1:09:02 PM: Creating new release with version:  5c5370d258279e0cb7ec7de10a651239f5fffb96
> 1:09:02 PM: ​
> 1:09:02 PM: ────────────────────────────────────────────────────────────────
> 1:09:02 PM:   Plugin "@sentry/netlify-build-plugin" internal error          
> 1:09:02 PM: ────────────────────────────────────────────────────────────────
> 1:09:02 PM: ​
> 1:09:02 PM:   Error message
> 1:09:02 PM:   Error: Command failed: /opt/build/repo/.netlify/plugins/node_modules/@sentry/cli/sentry-cli releases new 5c5370d258279e0cb7ec7de10a651239f5fffb96
> 1:09:02 PM:   error: API request failed
> 1:09:02 PM:     caused by: sentry reported an error: bad gateway (http status: 502)
> 1:09:02 PM: ​
> 1:09:02 PM:   Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
> 1:09:02 PM:   Please attach the full debug log to all bug reports.
> 1:09:02 PM: ​​
> 1:09:02 PM:   Plugin details
> 1:09:02 PM:   Package:        @sentry/netlify-build-plugin
> 1:09:02 PM:   Version:        1.0.4
> 1:09:02 PM:   Repository:     git+https://github.com/getsentry/sentry-netlify-build-plugin.git
> 1:09:02 PM:   npm link:       https://www.npmjs.com/package/@sentry/netlify-build-plugin
> 1:09:02 PM:   Report issues:  https://github.com/getsentry/sentry-netlify-build-plugin/issues
> 1:09:02 PM: ​
> 1:09:02 PM:   Error location
> 1:09:02 PM:   In "onPostBuild" event in "@sentry/netlify-build-plugin" from netlify.toml
> 1:09:02 PM:       at ChildProcess.exithandler (child_process.js:303:12)
> 1:09:02 PM:       at ChildProcess.emit (events.js:310:20)
> 1:09:02 PM:       at maybeClose (internal/child_process.js:1021:16)
> 1:09:02 PM:       at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> 1:09:02 PM: ​
> 1:09:02 PM:   Error properties
> 1:09:02 PM:   {
> 1:09:02 PM:     killed: false,
> 1:09:02 PM:     code: 1,
> 1:09:02 PM:     signal: null,
> 1:09:02 PM:     cmd: '/opt/build/repo/.netlify/plugins/node_modules/@sentry/cli/sentry-cli releases new 5c5370d258279e0cb7ec7de10a651239f5fffb96'
> 1:09:02 PM:   }
> ```

did you fix this can you let me know the steps if it's been fixed

**Comment by leeandher** [comment]
This hasn't been resolved yet but I will make sure it makes it onto our backlog. I'll be closing this ticket out in favour of #25 , since transitioning the plugin to `onSuccess` will allow a successful Netlify deploy even if there is a plugin failure. With that change, your deploys shouldn't be affected by unexpected Sentry downtime. 


Thank you for your patience!
