### ISSUE TITLE
Error `No repositories are configured in Sentry for your organization.`

### ISSUE THREAD

**Issue by ehmicky** [getsentry/sentry-netlify-build-plugin#4]
The following error happens in some builds:

```
Command failed: /opt/buildhome/.netlify-build-plugins/node_modules/@sentry/cli/sentry-cli releases set-commits d0dda9d322a710af170f67ff926ff3eb4115889b --commit chrisotto6/chrisottodev@d0dda9d322a710af170f67ff926ff3eb4115889b
error: No repositories are configured in Sentry for your organization.

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
 
    child_process.js:303:12 ChildProcess.exithandler
    events.js:310:20 ChildProcess.emit
    internal/child_process.js:1021:16 maybeClose
    internal/child_process.js:286:5 Process.ChildProcess._handle.onexit
```

I am assuming this might indicate a user error, in which case #3 might be related as well.

What do you think?

**Comment by jonesphillip** [comment]
> No repositories are configured in Sentry for your organization.

@ehmicky This happens when a repository or repository integration is not configured.

See: https://docs.sentry.io/workflow/releases/?platform=python#install-repo-integration

So yes, user configuration error. If you wish to not track commits, you can always use the `skipSetCommits` input.
