### ISSUE TITLE
Error: Unknown repo jasikpark/live-collegemusic-co-uk/

### ISSUE THREAD

**Issue by jasikpark** [getsentry/sentry-netlify-build-plugin#41]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
JS 6.2.1

### Steps to Reproduce

Setup the netlify plugin with correct environmental variables

### Expected Result

A successful build

### Actual Result

I got a couple of successful builds, but I suddenly am getting an error due to problems with my git remote format I expect:

```
7:41:34 PM: Error: Command failed: /opt/build/repo/.netlify/plugins/node_modules/@sentry/cli/sentry-cli releases set-commits 9b1c9d17e757dc8f7ac1dde3a5abceefa297667a --commit jasikpark/live.collegemusic.co.uk@9b1c9d17e757dc8f7ac1dde3a5abceefa297667a
7:41:34 PM: error: Unknown repo 'jasikpark/live.collegemusic.co.uk'
```

```
$ git remote -v
origin  git@github.com:jasikpark/live.collegemusic.co.uk.git (fetch)
origin  git@github.com:jasikpark/live.collegemusic.co.uk.git (push)
```

**Comment by jasikpark** [comment]
Similar to #6

**Comment by jonesphillip** [comment]
@jasikpark Saw your comment on the other issue. Let me know if adding your repo as well as the integration works. Try step 3 here:  https://docs.sentry.io/product/releases/setup/release-automation/

**Comment by jonesphillip** [comment]
Closing based on comment in #6
