### ISSUE TITLE
Staging vs Production

### ISSUE THREAD

**Issue by stippets** [getsentry/sentry-netlify-build-plugin#5]
We have both a staging and production environment that both look at the same repo but different branches. How can we control it so Sentry isn't run on our Netlify staging environment? I tried only installing the plugin via the Netlify UI on production, but build fail stating that there are required inputs which you can't seem to configure in Netlify UI. I had them set as environment variables (`SENTRY_ORG` and `SENTRY_PROJECT`) but the build still failed stating that `inputs.sentryOrg` is a required input.

**Comment by jonesphillip** [comment]
@stippets addressed. Will get it on npm in the next release by tomorrow.

https://github.com/getsentry/sentry-netlify-build-plugin/pull/7

**Comment by jonesphillip** [comment]
@stippets just wanted to confirm, you should be all good! Sorry about the inconvenience there
